config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "tasks", to: "tasks#index", as: :tasks

  get "tasks/new", to: "tasks#new", as: :new

  get "tasks/:id", to: "tasks#show", as: :task

  post "tasks", to: "tasks#create"

  get "tasks/:id/edit", to: "tasks#edit" , as: :edit

  patch "tasks/:id", to: "tasks#update"

  delete "tasks/:id", to: "tasks#destroy", as: :destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @tasks = Task.create(task_params)
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit a Punishing Task</h1>


<%= form_for @task do |task_form| %>
  Title: <%= task_form.text_field :title %>
  Details: <%= task_form.text_field :details %>
  Completed: <%= task_form.check_box :completed %>
  <%= task_form.button %>
<% end %>

<br>
<p><%= link_to "< Back", tasks_path %></p>

app/views/tasks/index.html.erb
<h1>🤜 Task Master 🤛</h1>


<% @tasks.each do |task| %>
  <%if task.completed == false%>
  <% r = "❎" %>
  <% else %>
  <% r = "✅" %>
  <% end %>

  <ul>
    <li><%=r %> <%= link_to task.title, task_path(task) %>, <%=task.details%>
      <%= link_to "🗑", task_path(task),
      method: :delete,
      data: { confirm: "Are you sure?" } %>
    </li>
  </ul>
<% end %>


<p><%= link_to "Create New", new_path %></p>





<!-- <li><%#=r %> <%#= link_to task.title, task.id_path %>, <%#=task.details%></li> -->

app/views/tasks/new.html.erb
<h1>Create a Punishing Task</h1>


<%= form_for @task do |task_form| %>
  Title: <%= task_form.text_field :title %>
  Details: <%= task_form.text_field :details %>
  Completed: <%= task_form.check_box :completed %>
  <%= task_form.button %>
<% end %>

<br>
<p><%= link_to "< Back", tasks_path %></p>

app/views/tasks/show.html.erb
<%if @task.completed == false%>
  <% r = "❎" %>
  <% else %>
  <% r = "✅" %>
  <% end %>


<h1><%= r %> - <%= @task.title %></h1>
<p><%= @task.details %></p>

<p><%= link_to "Edit this listing", edit_path(@task)%></p>


<br>
<p><%= link_to "< Back", tasks_path %></p>